### PR TITLE
Modularization of ELPI generation

### PR DESCRIPTION
**Pull request by jfschaefer**
The goal of this was to clean up the ELPI generation code and allow for more customization of what gets generated.
For that the exporter code has been separated into different handlers that can be added as needed.

I'm not at all sure about the design decisions I made. But I do believe that it is desirable to move towards a more modular architecture. Any feedback is welcome :)

### CODE REVIEW

**Comment by jfschaefer** [comment]
As discussed in the kwarc meeting, I will merge this.

**Comment by lambdaTotoro** [comment]
Do we still need the elpi2 branch for something or can that go?

**Comment by jfschaefer** [comment]
I just forgot to delete it after merging. It should be removed now

**Comment by lambdaTotoro** [comment]
It is, thank you. I was wondering if there's any unmerged changes lying around that I wasn't aware of, but apparently not so.

**Pull request merged**
