### PR TITLE
Add Sourceable trait and toSourceString methods

### PR DESCRIPTION
**Pull request by tkw1536**
This commit adds a toSourceString() method to all objects inside of MMT.
It is supposed to turn an object into a string that is equivalent to the
scala source code of the object.

Objects importing this method implement a new Sourceable trait. The
trait comes together with a type-safe application to all objects. 

/cc @florian-rabe @Jazzpirate

### CODE REVIEW

**Comment by florian-rabe** [comment]
As I said on skype, before merging this we should check if it can be done generically with Scala reflection instead.

For example, we could use showCode and related methods.

**Comment by tkw1536** [comment]
The problem with methods like ```showCode``` (or similar reflection methods) is that they
* produce pseudo-code that does not actually run, and
* are not type-safe, that is they can be applied to anything. This usually directly implies the above, as they do not look closer in the type that is given to them and assume that it can just be printed in a straightforward way (which is not always the case for classes in MMT).

**Comment by florian-rabe** [comment]
The specification of showCode says that the returned string is guaranteed to compile.

Type safety is lost anyway if we compute a string.

**Comment by florian-rabe** [comment]
case class A(a: Int, b: String)
case class B(a: A, b: A)

object HelloWorld {
   def main(args: Array[String]) {
     import reflect.runtime.universe._
     println(showCode(reify(B(A(1,"a"), A(2,"b"))).tree))
   }
}

**Comment by tkw1536** [comment]
You are correct, this is a much easier implementation. With https://github.com/UniFormal/MMT/commit/10b738270378e4d8066800e758c169d53bfde25c I have updated the code accordingly.

**Pull request merged**
