### PR TITLE
Improved license

### PR DESCRIPTION
**Pull request by dginev**
Cleaned up license to follow academic best practices. cc @florian-rabe 

(mostly for fun, but if you like it - feel free to merge!)

### CODE REVIEW

**Comment by tkw1536** [comment]
lgtm

**Comment by dginev** [comment]
This looks particularly amazing on GitHub, as they show a very sexy preview of standard licenses:
selection_015

**Comment by florian-rabe** [comment]
I wrote the license myself because I didn't like any of the existing ones.

Changes are possible but would require stronger reasons.

**Comment by florian-rabe** [comment]
Is there a way to get GitHub to display the set of permissions that corresponds to our current license?

**Comment by tkw1536** [comment]
> I wrote the license myself because I didn't like any of the existing ones.
> Changes are possible but would require stronger reasons.

I want to elaborate on this a bit, and give my reasons for why I am in favour of choosing a different license. 

MMT is an academic software and many papers have been written about it. 
As such, it is under constant development and is also indirectly subject to peer review. 

I believe that one of the core advantages of this process is to get feedback from the community on MMT, in particular to evaluate how it works at the current time and give suggestions, in conceptual and code form, on how to improve it and make it better in the future. 

### The Freedom of Free Software

The way I see it, this means that MMT should be free software. Specifically, free software as in the [Free Software Foundation definition](https://www.gnu.org/philosophy/free-sw.html.en). 
This is de-facto standard for all academically developed software. 

This includes four principal freedoms:
> * The freedom to run the program as you wish, for any purpose (freedom 0).
> * The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). 
> * The freedom to redistribute copies so you can help your neighbor (freedom 2).
> * The freedom to distribute copies of your modified versions to others (freedom 3). 

Freedoms 0 and 2 are fairly self-evident -- we want users to adapt MMT. 
Everyone wants to be able to run MMT and be able to distribute it -- otherwise why develop it in the first place?

Freedom 1 is an essential part of the peer review process. 
To judge if an implementation of a new algorithm or approach is well thought through, it is necessary to study the details of the implementation. 

This leaves only freedom 3 -- the right to distribute modified versions. 
This is very much intertwined with the peer review process, but mostly applies to general community improvements of MMT. 
When making suggestions for improvements, users may suggest an alternative implementation of parts of the code. 

This will usually require testing or some other form of evaluation. 
This can be done a single persons computer, but should usually involve sending out the improved version to other people (including the original authors), so one can see if the improvements are worth reintegrating into the core. 
For this it is essential to have the right to distribute modified versions -- otherwise no such improvements can ever be reintegrated as it is not allowed to send the modified code back to the original author(s). 

### Current State of The MMT license

The current [License of MMT](https://github.com/UniFormal/MMT/blob/master/COPYING.txt) provides redistribution of MMT provided a few conditions are met. This gives freedoms 0, 1 and 2 subject to certain conditions. 

Obviously this does not provide freedom 3 - which is a problem. 
In fact, this provides a legal obstacle to the current development process. 

I have already mentioned in [Issue #206](https://github.com/UniFormal/MMT/issues/206) how this conflicts with the GitHub terms and conditions (I will not repeat this here). E.g. it means neither of us is allowed to make local modifications and then deploy a modified version on MathHub. 
This is distribution of a modified copy in binary form from a local developer machine to a 'production' server and thus not allowed. 

Furthermore, as nothing in the license permits modification, no one is even allowed to change any of the code any other developer has written and pushed to GitHub. This is again is the distribution of modified code. The license clearly does not permit this -- only unchanged versions may be modified. 

The [explanation of the license](http://uniformal.github.io/doc/setup/license.html) makes, amongst others, this suggestion about changes:

> Ask if you can contribute your changes to MMT. MMT is meant to attract a community of develoers. 

Reiterating myself here. 
To make a contribution back into the core, the proposed change needs to be communicated back to the original developers. 
Communicating back modified code amounts to distribution of a modification -- and this is not permitted by the license. 

Even neglecting this point, there still is a problem. 
To ``attract a community of developers``, it is most certainly necessary to experiment with new implementations. 
Again I see the requirement that no modifications may be distributed as a major obstacle to this goal. 

A very common approach is to write a new plugin to MMT, only to later on figure out that the functionality should actually be in the core. 
But this can only be discovered if this custom plugin can be maintained outside the core first. 
This means that other developers want to have access to it -- play around with it, perhaps even change it. 
Only after some time can a community reach the conclusion that it should go directly into the core. 

But this can never happen, because none of this `playing around` is possible in the first place. 
None of the new experimental code can be distributed. 

It feels like this license is shooting ourselves in the foot -- no one can make any changes except the original author of each of the individual parts of code. 

> Acquiring the sources of a modification is a negligible amount of the work - essentially all the work lies in merging multiple modifications. The MMT license makes sure that modifiers also do the work of merging their modifications back into the MMT code base.

I agree with the first sentence. 
Yes -- reintegrating changes into the core takes time. 
But there is a major flaw in the thought process here:
It assumes that all changes are worth being reintegrated. 
This is not always the case, and not obvious in the beginning. 

If all modifications need to happen in the core -- ignoring how this is made possible -- this will lead to premature implementations and frequent undoings of code. 
But I believe that if something is worth being reintegrated, no matter how complicated, then someone will invest the time of merging it back. 
After all, such a time will be well-spent as it improves MMT. 

> * Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

As far as I am aware, none of the MMT JARs produce the list of conditions when distributed on their own. Thus they always have to be distributed with the full license text attached -- which is not the case and technically another violation of the license. 

### Alternative Licenses

I hope the above has at least convinced you that there are problems with forbidding distribution of modifications. 
If not, then there is no point to reading further, and I see no reason to continue the discussion. 

What @dginev suggested here is making the code public domain. 
Obviously, this allows any kind of modifications, and any kind of redistribution, without conditions. 
This certainly solves the problems and inconsistencies mentioned above. 

I see how being public domain can be a problem however. 
Preventing a major split of the code base is a worthwhile goal. 

Notice how I said major here. 
Minor changes are those that can be merged back in easily and are not a problem. 
I do not see how a major split of the MMT codecase would occur. 
Currently, and also in the near future, all expertise of MMT code lies within the KWARC group. 
Thus it is unlikely that anyone of us will actually make a fork. 
This together with the fact that the difference between major and minor changes is hard (if not impossible) to defined in a legal setting leads me to believe that the distribution of changed versions of MMT should be permitted by whatever license we choose. 

Licenses which require attribution -- like [GPL](https://www.gnu.org/licenses/gpl.html) or [MIT](https://opensource.org/licenses/MIT) -- can actualluy make a good compromise here.  
They allow any kind of modifications and at the same time make sure that the modifications stay minor and 'close' to the original code base. 
This is achieved by making sure that the modifications refer back to the original authors and -- in some cases -- even require all changes to be described. 
Either forces the new authors to keep the original authors and code base in mind -- either by recalling the authors names or by making sure to explicitly describe what is different. 

This all leads me to believe that a lot of the standard licenses is sufficient for MMT. A very good summary is provided by [Choose A License](https://choosealicense.com/). 

### GitHub License display
> Is there a way to get GitHub to display the set of permissions that corresponds to our current license?

No, GitHub can not display custom license information - and this makes perfect sense to me. 

First of all, writing custom licenses is always difficult. 
As seen from the above, it can easily lead to contradictions and should probably involve a lawyer (which we are not). 

Consider for a moment that it could. 
Then it would have to do one of the following things:

1. Infer license conditions given the license text
2. Allow to specify conditions without a license text

#### Inferring License conditions

One approach is using AI to understand and automatically infer license conditions -- infeasible for obvious reasons. 

Another approach is to allow users to set the conditions manually in some form.
This can obviously lead to a difference between the license text and what the display of conditions says. 
People are not lawyers and custom licenses will often not work as intended -- especially if they have not been tested in court. 
This can be seen from the problems displayed above. 

#### Specifying conditions only

This would be very confusing - users would be given conditions but due to a lacking license text these would never be enforceable. 
This problem is effectively solved by [Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons) -- which allows copyright holders to specify the conditions they want and then get a license text from that. 

/cc @kohlhase @florian-rabe @dginev

**Comment by dginev** [comment]
LaTeXML is essentially licensed in the Public Domain, and has had a very happy time proliferating and growing its ecosystem of users. There are all kinds of non-mainstream forks now just on GitHub, and that is a great thing, since a lot of the modifications are not immediately useful back upstream, but are good-to-haves in some subdomain. Upstream tends to hold all universally useful features, which works out lovely.

Given MMT is if anything _more_ of an expert software suite than LaTeXML, the obvious problem would be to get more people to use it, rather than restrict use to fewer, at least the way I see it. Using some open-friendly license facilitates that nicely. I mean even some GPL is fine, I recall Michael is fond of the copyleft approach. But there should be no real reason for a custom license, which to the rest of the world defaults as "stay away, or get a lawyer".

**Comment by jbetzend** [comment]
I agree that we really should get a new license. My reasoning is mainly this:

- There's no point in having a license that we're constantly violating ourselves and no point in having a license that says something different than what we actually want.
- As mentioned already by @tkw1536 in [Issue #206](https://github.com/UniFormal/MMT/issues/206), the current one technically goes against GitHub's Terms of Service.
- Relying on a standard license instead of homebrew gives security, both for us (we don't have to guess what might and might not be possible to do with MMT) and for potential external developers (who can safely infer what they can and can't do with the source).
- To attract these external developers in the first place, and further the adaptation from MMT outside of KWARC (a stated goal of the project), software freedom 3 as above is absolutely essential.

As far as I see it, there's some minor downsides and annoyances associated with keeping and some minor, but potentially bigger upsides with replacing the current license. We should do that.

My vote goes to CC0 as suggested in this PR or something relatively open like BSD or MIT. More specifically, we could also just straight up fall back on BSD 3 clause, on which the current license is based.

**Comment by tkw1536** [comment]
I would very much appreciate if this could be resolved sooner rather than later. As it stands right now, we are legally only allowed to distribute UNMODIFIED versions of the code, i.e. we have no legal basis on which we are allowed to change any of the code in MMT in future commits and distribute them.

**Comment by florian-rabe** [comment]
I don't see a problem here.

The "without modification" clause is meant to

* prevent people from distributing bad branches/forks/copies of the system
* force anybody who branches/forks/copies to pay the price of merging their changes back.

**Comment by tkw1536** [comment]
@florian-rabe That may be what its meant to do, but that's not what it does.

Licenses aren't "do as I mean", they are literal. And the literal definition of modification is any kind of change, no mention of if it's from a commit in the MMT repository, or anywhere else. If you want it to mean something different, it has to be defined as such in the license.

**Comment by tkw1536** [comment]
Reopened because of continued relevance. To quote @jbetzend:
> To attract these external developers in the first place, and further the adaptation from MMT outside of KWARC (a stated goal of the project), software freedom 3 as above is absolutely essential.

**Pull request closed without merging**
