### PR TITLE
Created GF importer

### PR DESCRIPTION
**Pull request by jfschaefer**
It can be used to import GF (Grammatical Framework) abstract syntaxes.

### CODE REVIEW

**Comment by tkw1536** [comment]
LGTM, the test failures are also present on master.

**Comment by tkw1536** [comment]
Any objections against squashing and merging this?

**Comment by jfschaefer** [comment]
> Any objections against squashing and merging this?

No objections from my side

**Comment by tkw1536** [comment]
@jfschaefer I've merged this -- please delete the branch at your convenience unless it's still needed for some reason.

**Pull request merged**
